gfl_language/views.py
from flask import Blueprint, render_template, request, flash, jsonify, session, redirect, url_for
from flask_login import login_required, current_user
from .models.user import Conversation, User, Note
from . import db
import json
from .utils.openai_funcs import example_prompt, generate_system_message, get_response, related_prompt
from .utils.organize_notes_gpt import get_notes

views = Blueprint('views', __name__)

temperature = 0.7
model = "gpt-3.5-turbo-1106"
obj_language, answer_language = 'English', 'Chinese'

@views.route('/', methods=['GET', 'POST'])
def index():
    answer = None
    user_logged_in = 'user_id' in session  # Check if user is logged in

    if request.method == 'POST':
        question = request.form['question']
        # Assuming process_question is a function that handles the question
        # answer = process_question(question)

    return render_template('index.html', answer=answer, user_logged_in=user_logged_in)

@views.route('/change_language', methods=['POST'])
@login_required
def change_language():
    new_language = request.form['language']
    
    # Update the user's preferred language in the database
    if current_user.is_authenticated:
        current_user.preferred_answer_language = new_language
        db.session.commit()
        flash('Language updated successfully.')
    else:
        flash('User not found.')

    return redirect(url_for('views.dashboard'))

'''
@views.route('/', methods=['GET', 'POST'])
@login_required
def home():
    if request.method == 'POST': 
        note = request.form.get('note')#Gets the note from the HTML 

        if len(note) < 1:
            flash('Note is too short!', category='error') 
        else:
            new_note = Note(data=note, user_id=current_user.id)  #providing the schema for the note 
            db.session.add(new_note) #adding the note to the database 
            db.session.commit()
            flash('Note added!', category='success')

    return render_template("home.html", user=current_user)
'''

@views.route('/get-answer', methods=['POST'])
def get_answer():
    system_message = generate_system_message(obj_language, answer_language)
    question = request.form.get('question')
    
    if 'message_list' not in session:
        session['message_list'] = [{"role": "system", "content": system_message}]

    session.modified = True    
    session['message_list'].append({"role": "user", "content": question})
    answer = get_response(session['message_list'], temperature, model)

    session.modified = True
    session['message_list'].append({"role": "assistant", "content": answer})

    print(session['message_list'])
    
    return jsonify({'answer': answer})

@views.route('/get-examples', methods=['POST'])
def get_examples():
    session.modified = True
    session['message_list'].append({"role": "user", "content": example_prompt})
    answer = get_response(session['message_list'], temperature, model)

    session.modified = True
    session['message_list'].append({"role": "assistant", "content": answer})
    
    return jsonify({'answer': answer})

@views.route('/get-related', methods=['POST'])
def get_related():
    session.modified = True
    session['message_list'].append({"role": "user", "content": related_prompt})
    answer = get_response(session['message_list'], temperature, model)

    session.modified = True
    session['message_list'].append({"role": "assistant", "content": answer})
    
    return jsonify({'answer': answer})

@views.route('/delete-notes')
def delete_notes():
    if current_user.is_authenticated:
        try:
            # Delete all notes for the current user
            Note.query.filter_by(user_id=current_user.id).delete()
            
            # Commit the changes to the database
            db.session.commit()

            flash('All notes have been successfully deleted.', 'success')
        except Exception as e:
            # Handle exceptions
            db.session.rollback()
            flash(f'An error occurred: {e}', 'error')

        return redirect(url_for('views.notes'))
    else:
        return redirect(url_for('auth.login'))

@views.route('/generate-notes', methods=['POST'])
def generate_notes():
    notes = get_notes(obj_language, answer_language, session['message_list'], temperature, model)
    print(notes)

    session['notes'] = notes
    # add notes from session to database

    new_note = Note(content=notes, user_id=current_user.id)
    db.session.add(new_note)
    db.session.commit()


    return jsonify({'notes': notes})

@views.route('/notes')
def notes_page():
    if current_user.is_authenticated:
        notes = current_user.notes
        print(notes)
        return render_template('notes.html', notes=notes)
    else:
        return redirect(url_for('auth.login')) 


#@views.route('/notes')
#def notes_page():
#    if current_user.is_authenticated:
        #print(session['message_list'])
#        notes = get_notes(obj_language, answer_language, session['message_list'], temperature, model)
#        print(notes)
#        return render_template('notes.html', notes=notes)
#    else:
#        return redirect(url_for('auth.login'))  # Redirect to login if user not logged in

@views.route('/tests')
def tests_page():
    user_logged_in = 'user_id' in session
    if user_logged_in:
        return render_template('tests.html')
    else:
        return redirect(url_for('auth.login'))
    

@views.route('/dashboard')
@login_required
def dashboard():
    return render_template('dashboard.html', user=current_user)


@views.route('/delete-note', methods=['POST'])
def delete_note():  
    note = json.loads(request.data) # this function expects a JSON from the INDEX.js file 
    noteId = note['noteId']
    note = Conversation.query.get(noteId)
    if note:
        if note.user_id == current_user.id:
            db.session.delete(note)
            db.session.commit()
            flash('Note deleted successfully.', category='success')
    
    return jsonify({"message": "Note deleted successfully", "status": "success"})




@views.route('/logout')
def logout():
    # Remove all data from the session
    session.clear()
    return redirect(url_for('auth.login'))

gfl_language/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />

    <title>{% block title %}Home{% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbar"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar">
        <div class="navbar-nav">
          {% if user.is_authenticated %}
          <a class="nav-item nav-link" id="home" href="/">Home</a>
          <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
          {% else %}
          <a class="nav-item nav-link" id="login" href="/login">Login</a>
          <a class="nav-item nav-link" id="signUp" href="/sign_up">Sign Up</a>
          {% endif %}
        </div>
      </div>
    </nav>

    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages %} {% if category ==
    'error' %}
    <div class="alert alert-danger alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% else %}
    <div class="alert alert-success alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}

    <div class="container">{% block content %} {% endblock %}</div>
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>

{% block javascript %}
    <script type="text/javascript">
      function deleteNote(noteId) {
  fetch("/delete-note", {
    method: "POST",
    body: JSON.stringify({ noteId: noteId }),
  }).then((_res) => {
    window.location.href = "/";
  });
  }
</script>
{% endblock %}
  </body>
</html>

gfl_language/templates/dashboard.html
<!DOCTYPE html>
<html>
<head>
    <title>Dashboard</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4; /* Light grey background */
            color: #333; /* Darker text for better readability */
        }
        .dashboard-container {
            width: 80%;
            margin: auto;
            background-color: #fff; /* White background for the container */
            padding: 20px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1); /* subtle shadow */
        }
        .profile-section, .learning-tools, .settings {
            margin-bottom: 20px;
        }
        .card {
            border: 1px solid #ccc;
            padding: 15px;
            border-radius: 8px;
            background-color: #fafafa; /* Slightly off-white cards */
        }
        h2, h3 {
            color: #007bff; /* Blue headings */
        }
        button {
            background-color: #007bff; /* Blue button */
            color: white;
            border: none;
            padding: 10px 20px;
            border-radius: 5px;
            cursor: pointer;
            transition: background-color 0.3s ease;
        }
        button:hover {
            background-color: #0056b3; /* Darker blue on hover */
        }
        .back-button {
            background-color: #6c757d; /* Gray button for back */
            margin-bottom: 20px; /* Spacing */
        }
    </style>
</head>
<body>
    <div class="dashboard-container">
        <button class="back-button" onclick="history.back()">← Back</button>

        
        <div class="profile-section card">
            <h2>Welcome back, {{ user.first_name}}!</h2>
            <p>Email: {{ user.email }}</p>
            <!-- Add more user details here -->
        </div>
     
        <div class="settings card">
            <h3>Settings</h3>
            <p>Preferred Language: <span id="currentLanguage">{{ user.preferred_answer_language }}</span></p>
            <button onclick="showEditOptions()">Edit</button>
        
            <div id="languageOptions" style="display:none;">
                <form action="/change_language" method="post">
                    <label for="language">Change Language:</label>
                    <select name="language" id="language">
                        <option value="English" {% if user.preferred_answer_language == 'English' %} selected {% endif %}>English</option>
                        <option value="Chinese" {% if user.preferred_answer_language == 'Chinese' %} selected {% endif %}>Chinese</option>
                        <!-- Add more languages as options here -->
                    </select>
                    <input type="submit" value="Change Language">
                </form>
            </div>
            <!-- Add more settings here -->
        </div>
        
        <script>
            function showEditOptions() {
                var x = document.getElementById("languageOptions");
                if (x.style.display === "none") {
                    x.style.display = "block";
                } else {
                    x.style.display = "none";
                }
            }
        </script>
        
        

        <div class="learning-tools card">
            <h3>Your Learning Progress</h3>
            <!-- Dynamically populate user's learning progress -->
            <p>Current Level: {{ user.current_level }}</p>
            <!-- Add more progress details here -->
        </div>
    </div>
</body>
</html>

gfl_language/templates/index.html
<!DOCTYPE html>
<html>
<head>
    <title>Gateway to Fluent Language</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <!-- Additional head content -->
</head>
<body>
    <header>
        {% if current_user.is_authenticated %}
            <button id="settingsBtn">Settings</button>
        {% else %}
            <button id="loginBtn">Login</button>
            <button id="signupBtn">Signup</button>
        {% endif %}

        <!-- ... [previous HTML code] ... -->
        {% if current_user.is_authenticated %}
        <!-- Display additional options for logged-in users -->
        <a href="{{ url_for('views.notes_page') }}" target="_blank"><button>Notes</button></a>
        <!-- <a href="{{ url_for('views.tests_page') }}" target="_blank"><button>Tests</button></a> -->
        {% endif %}
    </header>
    

    <main>
        

        <div id="chatArea" style="height: 300px; overflow-y: auto; border: 1px solid #ccc; padding: 10px; margin-bottom: 10px;">
            <!-- Conversation messages will appear here -->
        </div>

        <div id="options" style="display: none; margin-bottom: 10px;">
            <button id="moreExamplesBtn">Give More Examples</button>
            <button id="relatedPhrasesBtn">Show Related Phrases/Words</button>
            <button id="generateNotesBtn">Generate Notes</button>
        </div>

        <div id="questionForm">
            <form id="questionSubmitForm" method="post">
                <input type="text" name="question" placeholder="Ask your English question" style="width: 80%;">
                <input type="submit" value="Submit" style="width: 19%;">
            </form>
        </div>
        
        <div id="answerSection">
            <!-- Answer will be displayed here after submission -->
        </div>

<div id="options" style="display: none;">
    <button id="moreExamplesBtn">Give More Examples</button>
    <button id="relatedPhrasesBtn">Show Related Phrases/Words</button>
    <button id="generateNotesBtn">Generate Notes</button>
</div>

<!-- ... [remaining HTML code] ... -->

    </main>

    <script src="{{ url_for('static', filename='js/main.js') }}"></script>
    <!-- Additional scripts -->
</body>
</html>

gfl_language/templates/login.html
{% extends "base.html" %} {% block title %}Login{% endblock %} {% block content
    %}
    <form method="POST">
      <h3 align="center">Login</h3>
      <div class="form-group">
        <label for="email">Email Address</label>
        <input
          type="email"
          class="form-control"
          id="email"
          name="email"
          placeholder="Enter email"
        />
      </div>
      <div class="form-group">
        <label for="password">Password</label>
        <input
          type="password"
          class="form-control"
          id="password"
          name="password"
          placeholder="Enter password"
        />
      </div>
      <br />
      <button type="submit" class="btn btn-primary">Login</button>
    </form>
    {% endblock %}
    

gfl_language/templates/notes.html
<!DOCTYPE html>
<html>
<head>
    <title>My Notes</title>
    <style>
        .note-container {
            margin: 20px;
            padding: 15px;
            border: 1px solid #ccc;
            border-radius: 8px;
            background-color: #f8f8f8;
            white-space: pre-wrap; /* To ensure long lines wrap */
        }
        .note {
            padding: 10px;
            margin-bottom: 15px;
            border-bottom: 1px solid #eee;
        }
        .note:last-child {
            border-bottom: none;
        }
        .delete-button {
            background-color: #ff6347; /* Tomato color */
            color: white;
            border: none;
            padding: 10px 20px;
            border-radius: 5px;
            cursor: pointer;
            margin-top: 20px;
        }
        .delete-button:hover {
            background-color: #e35d45; /* Darker shade for hover effect */
        }
    </style>
</head>
<body>
    <h1>Your Organized Notes</h1>
    <div class="note-container">
        {% for note in notes %}
        <div class="note">
            <pre>{{ note.content }}</pre>
        </div>
        {% endfor %}
    </div>

    <form action="{{ url_for('views.delete_notes') }}" method="POST">
        <button type="submit" class="delete-button" onclick="return confirm('Are you sure you want to delete all notes?');">Delete All Notes</button>
    </form>
    
</body>
</html>

gfl_language/templates/sign_up.html
{% extends "base.html" %} {% block title %}Sign Up{% endblock %} {% block
    content %}
    <form method="POST">
      <h3 align="center">Sign Up</h3>
      <div class="form-group">
        <label for="email">Email Address</label>
        <input
          type="email"
          class="form-control"
          id="email"
          name="email"
          placeholder="Enter email"
        />
      </div>
      <div class="form-group">
        <label for="firstName">First Name</label>
        <input
          type="text"
          class="form-control"
          id="firstName"
          name="firstName"
          placeholder="Enter first name"
        />
      </div>
      <div class="form-group">
        <label for="password1">Password</label>
        <input
          type="password"
          class="form-control"
          id="password1"
          name="password1"
          placeholder="Enter password"
        />
      </div>
      <div class="form-group">
        <label for="password2">Password (Confirm)</label>
        <input
          type="password"
          class="form-control"
          id="password2"
          name="password2"
          placeholder="Confirm password"
        />
      </div>
      <br />
      <button type="submit" class="btn btn-primary">Submit</button>
    </form>
    {% endblock %}
    

gfl_language/templates/tests.html
<!DOCTYPE html>
<html>
<head>
    <title>Tests</title>
    
</head>
<body>
    <h1>Coming Soon!</h1>
    

</body>
</html>